# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'DMPlayer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DMPlayer
pod 'Masonry', '~> 1.1.0'
end
